---
title: "Cheeseboard task analysis of caimg data"
output:
  html_document:
    df_print: paged
---


```{r}
library(dplyr)
library(readr)
library(tidyr)
library(stringr)
library(DT)

library(ggplot2)
library(cowplot)
gtheme = theme_minimal() + theme_cowplot() + 
  theme(text = element_text(size=18), axis.text = element_text(size=15))
```

```{r}
data_dir = '/mnt/DATA/Prez/cheeseboard/2019-02-learning/'
ca_img_result_dir = paste0(data_dir, 'joined_caimg/')
subject = '1BR'
gen_imgs_dir = '/tmp/'
traces_file = paste0(ca_img_result_dir, 'traces_and_positions.csv')
data = read.csv(traces_file)

```


```{r}
data = data %>%
  gather('cell', 'nevents', starts_with('events_')) %>%
  gather('trace_cell', 'norm_trace', starts_with('normTrace_')) 
data$cell = str_replace(data$cell,'events_[.]?','')
data$trace_cell = str_replace(data$trace_cell,'normTrace_[.]?','')
data = filter(data, cell == trace_cell) %>%
  select(-trace_cell)
data = data %>%
  gather('trace_cell', 'trace', starts_with('trace_')) 
data$trace_cell = str_replace(data$trace_cell,'trace_[.]?','')
data = filter(data, cell == trace_cell) %>%
  select(-trace_cell)
data$trace = as.double(data$trace)

data$cell = as.integer(data$cell)
data$inside_roi = data$inside_roi > 0
```

```{r}
ncells = unique(data$cell) %>% length

first_learning_day = min(as.Date(data$date))
last_day = max(as.Date(data$date))
max_trial = max(data$trial)
data = mutate(data, 
              learning_day = as.integer(as.Date(date) - first_learning_day + 1),
              trial_no = (learning_day - 1) * max_trial + trial)
```

Read reward locations per day
``` {r}
source('locations.R')
locations.df = read_locations(paste0(data_dir)) 
```
# Calcium events

Events per cell per day and trial
```{r}
events_total.df = data %>% 
  group_by(date, trial, cell, trial_no, learning_day) %>%
  summarise(total_events = sum(nevents), 
            duration_sec = max(timestamp) / 1000,
            mer = total_events / duration_sec) %>%
  arrange(cell, date, trial)

datatable(select(events_total.df, trial_no, cell, total_events, duration_sec, mer))
```
Correlation between trial no and no events
```{r}
events_total.df %>%
  group_by(date, cell) %>%
  summarise(mean.event.rate = sum(total_events) / ncells / mean(duration_sec)) %>%
  ggplot() +
  geom_line(aes(x=date, y=mean.event.rate, group=cell))
```



```{r}
events.df = filter(data, nevents > 0)
```

Events during run vs during stationary
```{r}
run.threshold = 0.6
events.df %>% 
  mutate(running = velocity > run.threshold) %>%
  group_by(cell, running) %>%
  summarise(nnevents=n()) %>%
  ggplot(aes(cell,nnevents)) +
    geom_bar(stat='identity', aes(fill=running), position='dodge')
  
```


## Place cells


```{r}
get_place_field_centre = function(events.df) {
  #x = weighted.mean(events.df$smooth_trans_x, events.df$norm_trace)
  #y = weighted.mean(events.df$smooth_trans_y, events.df$norm_trace)
  x = mean(events.df$smooth_trans_x)
  y = mean(events.df$smooth_trans_y)
  return(c(x, y))
}

get_dist = function(pt1, pt2_x, pt2_y) {
  dist = sqrt((pt1[1] - pt2_x)^2 + (pt1[2] - pt2_y)^2)
}
```

```{r warning=FALSE}
source('place_field.R')
cells = unique(data$cell) %>% sort
pci.df = data.frame(cell_id=numeric(), day=character(), pci=numeric())

standard.distance = function(pt_centre, x, y) {
  n = length(x)
  y = 0.6 * y  # keep ratio between x and y
  d = sqrt(sum((x - pt_centre[1])**2) / (n - 1) +
           sum((y - pt_centre[2])**2) / (n - 1))
  return(d)
}

days = seq(first_learning_day, last_day, by=1)
for (i in 1:length(days)) {
  for (cell_id in cells) {
    day.str = as.character(days[i])
    cell.df = filter(data, cell == cell_id, date == day.str) 
    cell.df$trial = as.factor(cell.df$trial)
    cell.events = filter(cell.df, nevents > 0) 
    field_centre = get_place_field_centre(cell.events)
    if (nrow(cell.events) > 5) {
      cell.df.run = filter(cell.df, velocity >= run.threshold)
      if (nrow(cell.df.run) > 5) {
        pf = getPlaceField(cell.df.run)
        pci = pf$pci
      } else {
        pci = 0
      }
      entropy = getPlaceField(cell.df.run)$entropy
      cell.events = mutate(cell.events, sd.dist = standard.distance(field_centre, smooth_trans_x, smooth_trans_y))
      pci.df = bind_rows(pci.df, data.frame(cell_id=cell_id, day=day.str, 
                                            pci=pci, entropy=entropy,
                                            nevents=nrow(cell.events),
                                            event_spread=cell.events$sd.dist[1],
                                            field_centre.x=field_centre[1],
                                            field_centre.y=field_centre[2]))
    }
  }
}

pci.df = arrange(pci.df, desc(pci))
datatable(pci.df) %>% 
  formatRound(c('pci', 'entropy', 'event_spread'),digits = 2) %>%
  formatRound(c('field_centre.x', 'field_centre.y'),digits = 0)
```


```{r}
geom_trace = function(df, alpha=0.1) {
  ndata = nrow(df)
  if (ndata == 0) {
    return(geom_segment())
  }
  start_row=2
  df = arrange(df, trial_id, timestamp)
  newdata = df[start_row:ndata-1,]
  newdata$next_smooth_trans_x = df$smooth_trans_x[start_row:ndata]
  newdata$next_smooth_trans_y = df$smooth_trans_y[start_row:ndata]
 
  p = geom_segment(data=newdata, aes(x=smooth_trans_x, y=-smooth_trans_y, 
                                   xend=next_smooth_trans_x, yend=-next_smooth_trans_y,
                                   group=trial_id),
                   alpha=alpha)
}
```

```{r}
geom_rewards = function(locations.df, subject, day=NULL, valence='Positive') {
  reward.df = filter(locations.df,
                     Animal==subject, 
                     Valence == valence)
  if (!is.null(day)) {
    reward.df = filter(reward.df, date==day)
  }
  rew.col = 'blue'
  if (valence == 'Negative') {
    rew.col = 'red'
  }
  geom_point(data=reward.df, aes(x=trans_x,y=-trans_y), shape=0,color=rew.col, 
             fill='white', size=7, stroke=5, alpha=0.6) 
}

```


Events location for each cell
```{r}
for (cell_id in unique(data$cell)) {
  single_trial = filter(events.df, cell==cell_id & velocity > run.threshold)
  trial_name = sprintf('Cell_%d', cell_id)
  cell.trace.df = filter(data, cell == cell_id)
  g = ggplot(single_trial) +
    geom_point(aes(x=smooth_trans_x, y=-smooth_trans_y, color=date, size=norm_trace)) +
    #geom_trace(cell.trace.df) +
    geom_rewards(locations.df, subject) +
    xlab(trial_name) +
    theme_void()
  out.path = paste0('/tmp/', trial_name, '.jpg')
  ggsave(filename=out.path, plot=g, height=4, width=7)
}
```

```{r}
pci.df = mutate(pci.df, cell_desc=paste0('Cell ', cell_id, 
                                        ' PCI=', round(pci,1), 
                                        ' sd dist.=', round(event_spread, 1), ' (cm)'))


show_trial_events = function(data.df, g) {
  events.df = filter(data.df, nevents > 0)
  events.joined = left_join(events.df, pci.df, by=c('date'='day', 'cell'='cell_id'))  %>%
    mutate(cell_desc = if_else(is.na(cell_desc), paste('Cell', as.character(cell)), cell_desc))
  
  trace.df = filter(data.df, cell == cells.selected[1])
  
  events.joined$cell_desc = as.factor(events.joined$cell_desc)
  events.joined$cell = as.factor(events.joined$cell)
  g = g + 
    geom_rewards(locations.df, subject, day.str, valence = 'Negative') +
    geom_rewards(locations.df, subject, day.str) +
    geom_point(data=events.joined, 
               aes(x=smooth_trans_x, y=-smooth_trans_y, 
                   color=trial_id, size=norm_trace), alpha=0.8) +
    geom_trace(trace.df, alpha=0.1) +
    xlim(c(1,100)) + ylim(c(-100,-1))
  return(g)
}

day.str = '2019-02-26'
cells.selected = 2
include_test = FALSE
g = ggplot()
for (trial_day in 1:7) {
  data.day.df = filter(data, date==day.str) %>%
                filter(cell %in% cells.selected) %>%
                filter(trial == trial_day) %>%
                filter(is_test == include_test)
  g = show_trial_events(data.day.df, g)
}
g
trial_name = paste(day.str, 'trial', trial_day, sep='_')
out.path = paste0('/tmp/', trial_name, '.jpg')
#ggsave(filename=out.path, plot=g, height=4, width=9)
```


Standard distance histogram
```{r}
g = pci.df %>%
  ggplot() +
  geom_histogram(aes(x=event_spread), binwidth = 2, fill='white',colour='blue') +
  #geom_vline(xintercept=spread.th, colour='red', linetype='dashed', size=2) +
  gtheme +
  xlab('Standard distance (cm)') + 
  ylab('# Cells')
g
ggsave(paste0(gen_imgs_dir, 'standard_distance.svg'), plot=g, width=3, height=3)
```

Centroids of spatially restricted cells
```{r}
spread.th = 20
spacial.cells = pci.df %>%
  filter(event_spread <= spread.th) 

spacial.cells$cell_id = as.factor(spacial.cells$cell_id)

ggplot() +
  #geom_point(data=data.frame(x=4,y=box.width.cm/2), aes(x=x,y=y), shape=0,color='blue', fill='white', size=7, stroke=5) +
  geom_point(data=spacial.cells, aes(x=field_centre.x, y=-field_centre.y, 
                                     size=2*(spread.th-0.5*event_spread), 
             colour=cell_id), alpha=0.6) +
  theme(text = element_text(size=18)) +
  ylim(c(-100, -1)) + xlim(c(1,100)) +
  geom_rewards(locations.df, subject, day.str) +
  scale_size(guide = FALSE) 

```



Reward distance
```{r}

```


Raster plot for events

```{r}
events.df = filter(data, nevents>0)
events.df$trial_id_num = as.integer(events.df$trial_id)
timestamp.max.df = events.df %>%
  group_by(trial_id_num) %>%
  summarise(timestamp.max=max(timestamp)) %>%
  arrange(trial_id_num) 
timestamp.max.df$timestamp.offset=cumsum(timestamp.max.df$timestamp.max)-timestamp.max.df$timestamp.max

events.df.abs = left_join(events.df, timestamp.max.df, by='trial_id_num') %>%
  mutate(timestamp.abs=timestamp.offset+timestamp)
  
#x = rep(0, sum(events.df$nevents))
#y = rep(0, max(data$cell))
#start.index = 1
#for (cell in 1:max(events.df$cell)) {
#  x[cell] = 
#}

ncell = max(events.df$cell)
raster.frame = select(events.df.abs, timestamp.abs, cell)
ggplot() +
  geom_vline(data=timestamp.max.df, aes(xintercept=timestamp.offset/1000), linetype='dashed', colour='red') +
  geom_tile(data=raster.frame, aes(timestamp.abs / 1000, cell), width=5) +
  xlab('Time [s]') + 
  ylab('Cell')


```

MFR
```{r}
events.df.abs %>%
  group_by(cell) %>%
  summarise(nevents=n() , n=n(), dur_sec=max(timestamp.abs)/1000) %>%
  summarise(mfr=mean(nevents/dur_sec), sdfr=sd(nevents/dur_sec)) %>%
  arrange(desc(mfr))
```

Show cell filter
```{r}
library(R.matlab)
library(magick)  
library(reshape2)
library(scales)
mat_file = paste0(ca_img_result_dir, subject,  '/jointExtraction/sorted/PCAICAsorted.mat')
ca.mat = readMat(mat_file)
filters = ca.mat[['filters']]
filters.selected = filters[,,cells.selected]
ncells = dim(filters)[3]
filters.thresholded = filters[,,] > 0.029
centroids = data.frame(cell=1:ncells, x=rep(0, ncells), y=rep(0,ncells), row.names = 1)
for (cell in 1:ncells) {
  dims = dim(filters[,,cell])
  pos = which.max(filters[,,cell])
  pos_x = pos %% dims[1]
  pos_y = floor(pos / dims[1]) + 1
  centroids[cell,] = c(pos_x, pos_y)
}
centroids$name = as.factor(rownames(centroids))

filters.projection = rowSums(filters.thresholded, dims=2)
#image(filters.projection, col = grey(seq(0, 1, length = 256)))

g=ggplot(centroids) +
  #geom_point(aes(x=x, y=y)) +
  geom_raster(data=melt(filters.projection), aes(x=Var2, y=-Var1,fill=value), show.legend=FALSE,
              colour="grey50") +
  geom_text(aes(y, -x, label=name), size=5) +
  scale_fill_gradient2(low='white', high='yellow') +
ggsave(paste0(gen_imgs_dir, 'centroids.svg'), g)
g

```
```{r}
day.str = '2018-10-30'
trial.df = filter(data, cell %in% cells.selected, date==day.str)
trial.df$cell_name=as.factor(trial.df$cell) %>% as.integer
trial.events.df = filter(trial.df, nevents > 0)
g = ggplot(trial.df) +
  geom_line(aes(x=timestamp/1000, y=norm_trace, group=1)) +
  geom_point(data=trial.events.df, aes(x=timestamp/1000, y=norm_trace + 1), shape=8, colour='red') +
  facet_grid(cell_name ~ .) +
  gtheme +
  xlab('Time (sec)') +
  ylab('z-scored dF/F') 

ggsave(paste0(gen_imgs_dir, 'traces.svg'), g)
g

```


```{r}
cell_id = 1
cell.df = filter(data, cell == cell_id, date == day.str) 
cell.events = filter(cell.df, nevents > 0) 
cell.df$trial = as.factor(cell.df$trial)

source('place_field.R')
place.df = getPlaceField(cell.df)
col.pallette = RColorBrewer::brewer.pal(9,"Blues")
image(place.df[['field']], col=col.pallette)
image(place.df[['occupancy']], col=col.pallette)
```

```{r}
field_centre = get_place_field_centre(cell.events)
trial.df = mutate(cell.df, 
                  field_dist = get_dist(field_centre, smooth_trans_x, smooth_trans_y),
                  reward_dist = pmin(dist_reward0, dist_reward1))
g=ggplot(trial.df ) +
  geom_line(aes(x=timestamp/1000, y=norm_trace, group=1)) +
  geom_line(aes(x=timestamp/1000, y=reward_dist/10, group=1), colour='blue') +
  geom_point(data=cell.events, aes(x=timestamp/1000, y=norm_trace + 1), shape=8, colour='red') +
  facet_grid(trial ~ .) +
  xlab('Time (sec)') +
  ylab('z-scored dF/F')  + gtheme
g
#ggsave(paste0(gen_imgs_dir, 'dist_reward_trace.svg'), g)
```


