---
title: "R Notebook"
output: html_notebook
---

Requires workspace data created by running Fig1-place_field_stats.Rmd
```{r}
load(file="data/place_field_stats.RData")
```

  
# Do cells have propoensity to be close to reward?
Model of cell randomly assigned at distances following observed distribution

```{r}
pc.ids = dplyr::group_by(beforetest.peaks.at.current.rew, implant, animal, cell_id) %>%
  dplyr::summarise(nsignif=sum(signif.si), 
                   n=n()) %>%
  dplyr::filter(n > 1) %>%
  dplyr::filter(nsignif/n >= 0.5) %>%
  dplyr::mutate(animal_cell = paste(animal, cell_id, sep='_')) 

cell.dist.df = beforetest.peaks.at.current.rew %>%
  dplyr::select(implant, animal, date, cell_id, min.rew.dist, rew.peaks.count) %>%
  dplyr::filter(paste(animal, cell_id, sep='_') %in% pc.ids$animal_cell) %>%
  dplyr::group_by(implant, animal, date)

nsamplings = 1000
set.seed(42)


shuffle.fun = function(v) {
  if (length(v) == 1) {
    return(v)
  }
  org.indecies = seq_along(v)
  shuffled.indecies = seq_along(v)
  # check no cell in the same order as current
  while (any((shuffled.indecies - org.indecies) == 0)) {
    shuffled.indecies = permute::shuffle(length(v))
  }
  v[shuffled.indecies]
}

shuffled.cell.dist.df = map_dfr(
  1:nsamplings, ~ dplyr::mutate(cell.dist.df, 
                                shuffle.id=.x,
                                shuffle.cell_id = shuffle.fun(cell_id))) %>%
  filter(!is.na(shuffle.cell_id))

shuffled.cell.dist.summary = shuffled.cell.dist.df %>%
  group_by(implant, animal, shuffle.cell_id, shuffle.id) %>%
  dplyr::summarise(m.dist = mean(min.rew.dist, na.rm=TRUE), 
                   n=sum(!is.na(min.rew.dist)), 
                   var.dist=var(min.rew.dist) / (n),
                   at.rew.times=sum(min.rew.dist <= goal.cell.max.dist),
                   rew.peaks.count=sum(rew.peaks.count)) %>%
  filter(n > 1) %>%  # only include cells present on at least two days
  dplyr::mutate(group='sampled', line_g=paste0(group, shuffle.id))
```

Number of fields at reward per cell compared to the number after the cell identities randomly shuffled 
```{r}
rew.peaks.pct.step = 20
few.fields.thr = 20
many.fields.thr = 50
shuffled.cell.dist.summary = mutate(shuffled.cell.dist.summary,
                                    rew.peaks.pct = rew.peaks.count / (n * 2) * 100)
shuffled.cell.dist.summary = as.data.table(shuffled.cell.dist.summary)

vca1.shuffle.ecdfs = map(unique(shuffled.cell.dist.summary$line_g), 
                         ~ ecdf(shuffled.cell.dist.summary[ line_g == .x & implant=='vCA1', rew.peaks.pct]))

vca1.ecdf.knots = map(vca1.shuffle.ecdfs, ~ knots(.x)) %>% unlist %>% sort %>% unique
vca1.shuffle.ecdf.summary.df = map_df(vca1.ecdf.knots, function(knot) {
  vals = map_dbl(seq_along(vca1.shuffle.ecdfs), ~ vca1.shuffle.ecdfs[[.x]](knot))
  list(knot=knot,
       mean.val=mean(vals),
       lower.val=quantile(vals, 0.05)[[1]],
       higher.val=quantile(vals, 0.95)[[1]])
})

dca1.shuffle.ecdfs = map(unique(shuffled.cell.dist.summary$line_g), 
                         ~ ecdf(shuffled.cell.dist.summary[ line_g == .x & implant=='dCA1', rew.peaks.pct]))

dca1.ecdf.knots = map(dca1.shuffle.ecdfs, ~ knots(.x)) %>% unlist %>% sort %>% unique
dca1.shuffle.ecdf.summary.df = map_df(dca1.ecdf.knots, function(knot) {
  vals = map_dbl(seq_along(dca1.shuffle.ecdfs), ~ dca1.shuffle.ecdfs[[.x]](knot))
  list(knot=knot,
       mean.val=mean(vals),
       lower.val=quantile(vals, 0.05)[[1]],
       higher.val=quantile(vals, 0.95)[[1]])
})

shuffled.cell.atrew.hist = shuffled.cell.dist.summary %>%
  group_by(implant, shuffle.id) %>%
  dplyr::summarise(create.hist.tibble(rew.peaks.pct, seq(0,100,rew.peaks.pct.step)))

# Percentile of cells in the shuffles with few and many fields
shuffled.pct.atrew.95p = shuffled.cell.atrew.hist %>%
  dplyr::mutate(few_fields = mid < few.fields.thr, many_fields = mid >= many.fields.thr) %>%
  dplyr::group_by(implant, shuffle.id, few_fields, many_fields) %>%
  dplyr::summarise(cell.pct=sum(pct.count)) %>% 
  dplyr::group_by(implant, few_fields, many_fields) %>%
  dplyr::summarise(cell.pct.05p = stats::quantile(cell.pct, 0.05)[1],
                   cell.pct.mean = mean(cell.pct),
                   cell.pct.95p = stats::quantile(cell.pct, 0.95)[1],
                   z=list(sort(cell.pct)))

shuffled.cell.atrew.hist.summary = shuffled.cell.atrew.hist %>%
  group_by(implant, mid) %>%
  dplyr::summarise(m.count=mean(pct.count), sem.count=sem(pct.count), sd.count=sd(pct.count))


cell.rew.distance.summary = beforetest.peaks.at.current.rew %>%                 
  filter(paste(animal, cell_id, sep='_') %in% pc.ids$animal_cell) %>%           
  dplyr::group_by(implant, animal, cell_id) %>%                                 
  dplyr::summarise(m.dist = mean(min.rew.dist),                                 
                   n=sum(!is.na(min.rew.dist)),                                 
                   nsignif=sum(signif.si, na.rm=TRUE),                          
                   var.dist=var(min.rew.dist) / (n),  # biased estimate for variance
                   at.rew.times=sum(min.rew.dist <= goal.cell.max.dist),        
                   rew.peaks.count=sum(rew.peaks.count)) %>%                    
  dplyr::mutate(group='actual', 
                line_g=group,
                rew.peaks.pct = rew.peaks.count / (n * 2) * 100)   

cell.rew.distance.summary.test = cell.rew.distance.summary


bind_rows(
  vca1.shuffle.ecdf.summary.df %>% mutate(implant='vCA1'),
  dca1.shuffle.ecdf.summary.df %>% mutate(implant='dCA1')) %>%
  ggplot() +
  geom_step(aes(x=knot,y=lower.val), color='#aaaaaa') +
  geom_step(aes(x=knot,y=higher.val), color='#aaaaaa') +
  stat_ecdf(data=cell.rew.distance.summary.test,
            aes(x=rew.peaks.pct), color=side.two.coulours[1], size=0.75) +
  xlab('Reward fields (%)') + ylab('Cells CDF') +
  facet_grid(. ~ implant) +
  gtheme
figure.ggsave('Figure_4E.pdf', height=4.0, width=6.5)

cell.rew.atrew.hist = cell.rew.distance.summary %>%
  group_by(implant) %>%
  dplyr::summarise(create.hist.tibble(rew.peaks.pct, seq(0,100,rew.peaks.pct.step)),
                   pct.count.cumsum = cumsum(pct.count))

vca1.freq.rew.fields = 100 - max(subset(cell.rew.atrew.hist, implant == 'vCA1' & mid < many.fields.thr)$pct.count.cumsum)
print('vCA1 Frequent rewards percentile')
mean(subset(shuffled.pct.atrew.95p, implant=='vCA1' & many_fields)$z[[1]] < vca1.freq.rew.fields)

dca1.freq.rew.fields = 100 - max(subset(cell.rew.atrew.hist, implant == 'dCA1' & mid < many.fields.thr)$pct.count.cumsum)
print('dCA1 Frequent rewards percentile')
mean(subset(shuffled.pct.atrew.95p, implant=='dCA1' & many_fields)$z[[1]] < dca1.freq.rew.fields)

cell.rew.atrew.hist.summary = cell.rew.distance.summary %>%
  group_by(implant) %>%
  dplyr::summarise(create.hist.tibble(rew.peaks.pct, seq(0,100,rew.peaks.pct.step)))

shuffled.cell.atrew.hist.summary %>%
  ggplot(aes(x=mid)) +
  geom_bar(aes(y=m.count),  stat='identity', position='dodge', width=rew.peaks.pct.step,
           fill='white', color='#666666', size=0.5) +
  geom_errorbar(aes(ymin=m.count-sd.count, ymax=m.count+sd.count), 
                width=rew.peaks.pct.step / 3, 
                color='#666666') +
  geom_step(data=cell.rew.atrew.hist.summary, aes(x=mid-rew.peaks.pct.step/2, y=pct.count), 
            color=side.two.coulours[1], size=0.75) +
  facet_wrap(. ~ implant) + ylab('Cells (%)') + xlab("Reward fields (%)") +
  labs(title="Count of cell's reward fields") +
  scale_x_continuous(breaks = seq(0, 100, rew.peaks.pct.step)) +
  gtheme
```


```{r}
shuffled.pct.atrew.95p
cell.rew.atrew.hist
```


## Cell recall
```{r}
beforetest.cell.recall = beforetest.peaks.at.current.rew %>%
  ungroup() %>%
  dplyr::select(animal, implant, exp_day_ordinal, cell_id, min.rew.dist) %>% 
  tidyr::pivot_wider(names_from=exp_day_ordinal, values_from=min.rew.dist, names_prefix='day') %>% 
  filter(!is.na(day9)) %>%
  tidyr::pivot_longer(-c(animal, implant, cell_id), names_to='exp_day_ordinal', names_prefix='day',
                      values_to='min.rew.dist') %>%
  filter(exp_day_ordinal != 15) %>%
  group_by(animal, implant, exp_day_ordinal) %>% 
  dplyr::summarise(ncells=n(),
                   recall.pct=sum(!is.na(min.rew.dist)) / ncells * 100) 

beforetest.cell.recall %>%
  dplyr::group_by(exp_day_ordinal) %>%
  dplyr::summarise(recall.mean = mean(recall.pct),
                   recall.sem = sem(recall.pct))

beforetest.cell.recall.summary = beforetest.cell.recall %>%
  dplyr::group_by(implant, exp_day_ordinal) %>%
  dplyr::summarise(recall.mean = mean(recall.pct),
                   recall.sem = sem(recall.pct))

beforetest.cell.recall.summary %>%
  ggplot(aes(x=as.integer(exp_day_ordinal), group=implant)) +
  geom_line(aes(y=recall.mean, color=implant)) +
  geom_ribbon(aes(ymin=recall.mean - recall.sem, 
                  ymax=recall.mean+recall.sem,
                  fill=implant), 
              alpha=0.3) +
  scale_fill_manual(values=main.two.colours) +
  scale_color_manual(values=main.two.colours) +
  scale_x_continuous(breaks=c(9,11,13)) +
  gtheme +
  ylim(c(0, 100)) +
  xlab('') + ylab('Recall (%)')

figure.ggsave('Figure_S4C.pdf', height=3.3, width=5.2)
```
