---
title: "R Notebook"
output: html_notebook
---
Plots activity traces of reward and non-reward cells

```{r setup}
library(dplyr)
library(pracma)
library(purrr)
library(readr)
library(tidyr)
library(stringr)
library(data.table)
library(datatrace)
library(tidyr)

source('locations.R')
source('utils.R')
source('traces_input.R')
source('plotting_params.R')
source('tracking_info.R')
source('behav_analysis.R')
source('reward_approach_activity_utils.R')

perc2dist = 1.2
```


```{r}
mouse.meta.df = read.mouse.meta(rootdirs)
trials.meta.df = read.trials.meta(rootdirs) %>%
  filter(animal %in% animal_names)
last.learning.days = c('learning1 day#5', 'learning2 day#2', 'learning3 day#2', 'learning4 day#2')
```


```{r}
root_dir = root_dir01
exp_title='learning'
day_desc_name = 'learning3 day#2'
animal_name = 'K-BR' # vCA1 example
#animal_name='F-BL' # vCA1 example

get.rew.aligned.traces = function(animal_name, day_desc_name, 
                                  min.bout.dur=3000, timebin.dur.msec=200) {

  day = filter(trials.meta.df, animal == animal_name, day_desc == day_desc_name) %>% pull(date)
  caimg_result_dir = find.caimg.dir(caimg_result_dirs, animal_name, day)
  binned.traces = prepare.binned.traces(caimg_result_dir, timebin.dur.msec=timebin.dur.msec)
  behav.traces = get.behav.traces(binned.traces)
  mobility.bouts = get.mobility.bouts(behav.traces, timebin.dur.msec=timebin.dur.msec,
                                      mobility.expr=is_running, min.bout.len.msec = min.bout.dur)
  reward.arriving.bouts = mobility.bouts[rew_at_end > 0,]
  rew.aligned.traces = binned.traces[exp_title=='trial', 
                                   center.timestamps.around.events(.SD, 
                                                                   reward.arriving.bouts,
                                                                   exp_title[1],
                                                                   padding.after.event=6000/timebin.dur.msec), 
                                   by=.(exp_title, trial_id, cell_id)][aligned_event_id >= 0,]
}


rew.aligned.traces = data.table::rbindlist(list(
  get.rew.aligned.traces(animal_name, day_desc_name, min.bout.dur = 3000)))

rew.aligned.traces$aligned_event_order = with(rew.aligned.traces, 
                                              as.factor(paste(date, rew_at_end, trial, aligned_event_id))) %>%
  as.integer()
```



```{r}
selected.cell_id = 220 # K-BR learning3 day#2 
#selected.cell_id = 89 # F-BL learning3 day#2

fill.var = quo(zscored_smooth_deconv_trace)
xvar = expr(timestamp_from_end/1000)
tile.width=timebin.dur.msec/1000

rew.aligned.traces %>%
  filter(cell_id == selected.cell_id) %>% 
  left_join(trials.meta.df) %>%
  filter(day_desc == day_desc_name) %>%
  ggplot() +
  geom_tile(aes(x=!!xvar, 
                y=aligned_event_order, 
                fill=!!fill.var),
            width=tile.width*2) +
  xlab('Time (s)') +
  ylab('Approach') +
  scale_x_continuous(limits=c(-5, 5), breaks=seq(-4,4,2)) +
  facet_wrap(rew_at_end ~ day_desc, scales = 'free_y', nrow=1) +
  gtheme +
  #theme(legend.position = 'none') +
  #scale_fill_gradient(low='white', high = 'black') +
  scale_fill_gradientn(colours = jet.colours(7)) + 
  #scale_fill_viridis_c(option='B') +
  scale_color_manual(values=c('#0098ffff', 'white')) +
  scale_y_reverse()

figure.ggsave('Fig4D-approach-traces-example.pdf',
               width=9.5, height=3.4)
```

Activity of reward cells vs other cells for the example animal and day
```{r}
min.timestamp.from.end = -6000
max.timestamp.from.end = 6000
beforetest.peaks.at.current.rew = as.data.table(beforetest.peaks.at.current.rew)
day = rew.aligned.traces$date[1]
reward.cells = beforetest.peaks.at.current.rew[date == day+1 & animal == animal_name & 
                                            signif.si & min.rew.dist <= goal.cell.max.dist, cell_id]
rew.aligned.traces$is.rew.cell = rew.aligned.traces$cell_id %in% reward.cells 
mean.rew.traces = rew.aligned.traces[timestamp_from_end >= min.timestamp.from.end & 
                                       timestamp_from_end <= max.timestamp.from.end, 
                   .(mean.trace=mean(zscored_smooth_deconv_trace), 
                     sem.trace=sem(zscored_smooth_deconv_trace),
                     n=.N), 
                   by=.(is.rew.cell, timestamp_from_end)] 
mean.rew.traces %>%
  ggplot(aes(x=timestamp_from_end/1000, y=mean.trace)) +
  geom_ribbon(aes(ymin=mean.trace-sem.trace, 
                  ymax=mean.trace+sem.trace, 
                  fill=is.rew.cell),
              alpha=0.3) +
  gtheme
```

```{r include=FALSE}
last.day.trials.df = expand.grid(animal=unique(trials.meta.df$animal), 
                                 day_desc_name=last.learning.days)

min.timestamp.from.end = -6000
max.timestamp.from.end = 6000
trial.peaks.at.current.rew = as.data.table(trial.peaks.at.current.rew)
beforetest.peaks.at.current.rew = as.data.table(beforetest.peaks.at.current.rew)
rew.aligned.traces.list = list()
for (i in 1:nrow(last.day.trials.df)) {
  rew.aligned.traces = get.rew.aligned.traces(last.day.trials.df$animal[i],
                                              last.day.trials.df$day_desc_name[i])
  
  day = rew.aligned.traces$date[1]
  cell_ids.present = beforetest.peaks.at.current.rew[date == day+1 &
                                                       animal == last.day.trials.df$animal[i],
                                                     cell_id]
                                              
  
  reward.cells = beforetest.peaks.at.current.rew[date == day+1 & 
                                                   animal == last.day.trials.df$animal[i] & 
                                                   signif.si & min.rew.dist <= goal.cell.max.dist, 
                                                 cell_id]
  rew.aligned.traces$is.rew.cell = rew.aligned.traces$cell_id %in% reward.cells 
  rew.aligned.traces.list[[i]] = rew.aligned.traces[
    timestamp_from_end >= min.timestamp.from.end & 
      timestamp_from_end <= max.timestamp.from.end &
      cell_id %in% cell_ids.present, ]
}
  
```

```{r}
all.rew.aligned.traces = rbindlist(rew.aligned.traces.list)
all.rew.aligned.traces = all.rew.aligned.traces[as.data.table(mouse.meta.df), on='animal']
all.rew.aligned.traces = all.rew.aligned.traces[animal %in% animal_names,]

mean.rew.traces = all.rew.aligned.traces[,
                   .(mean.trace=mean(zscored_smooth_deconv_trace), 
                     sem.trace=sem(zscored_smooth_deconv_trace),
                     n=.N), 
                   by=.(implant, is.rew.cell, timestamp_from_end)] 

timebin.width = 1000
all.rew.aligned.traces.comparison = all.rew.aligned.traces[
    (timestamp_from_end <= -4000) & (timestamp_from_end > -5000) |
    (timestamp_from_end > -1000) & (timestamp_from_end <= 0)][
    , timestamp_from_end_bin := ceiling(timestamp_from_end / timebin.width)] [
  !is.na(timestamp_from_end_bin) & !is.na(is.rew.cell) & !is.na(date)]
```

Calculate how many times a cell active
TODO: Choose a day
```{r}
cell.active.thr = 0.5

fraction.approaches.cell.active = 
  all.rew.aligned.traces[, timestamp_from_end_bin := ceiling(timestamp_from_end / timebin.width)][
                         timestamp_from_end_bin %in% c(-4, 0),
                         .(binned.activity = mean(zscored_smooth_deconv_trace)),
                         by=.(implant, exp_title, trial_id, cell_id, animal, date, trial, aligned_event_id, rew_at_end, timestamp_from_end_bin)][
                         ,
                       .(fraction.active = mean(binned.activity >= cell.active.thr),
                         napproaches = .N),
                       by=.(implant, exp_title, cell_id, animal, date, rew_at_end, timestamp_from_end_bin)]
```


```{r}
calc.ecdfs.summary = function(line_ids, fraction.active, group_name) {
  group.ecdfs = map(unique(line_ids), 
                    ~ { e = ecdf(fraction.active[which(line_ids == .x)])
                        list(e =e,
                             group = group_name,
                             knots.list = knots(e))
                        })
  #group.knots = map(seq_along(group.ecdfs), ~ knots(group.ecdfs[[.x]]$e)) %>% unlist
  # Add fixed knots for zero approaches and frequent approaches
  #group.knots = c(0.1, 0.5, group.knots) %>% sort %>% unique 
  group.knots = c(0.1, 0.5, seq(0, 1.0, 0.05)) %>% sort %>% unique
  group.ecdfs.summary.df = map_df(group.knots, function(knot) {
    vals = map_dbl(seq_along(group.ecdfs), ~ group.ecdfs[[.x]]$e(knot))
    list(knot=knot,
         group=group_name,
         mean.val=mean(vals),
         lower.val=quantile(vals, 0.05)[[1]],
         higher.val=quantile(vals, 0.95)[[1]])
  })
  bind_rows(group.ecdfs.summary.df,
            data.frame(knot=c(-0.01,1.01),
                       group=group_name,
                       mean.val=c(0,1),
                       lower.val=c(0,1),
                       higher.val=c(0,1)))
}

# ecdf.df = fraction.approaches.cell.active %>% 
#   left_join(trials.meta.df) %>%
#   left_join(place.cell.db) %>%
#   #filter(rew_at_end == 1) %>%
#   #filter(day_desc == 'learning1 day#5') %>%
#   #filter(day_desc == 'learning2 day#2') %>%
#   mutate(line_id=paste(implant, animal, day_desc, is.pc, rew_at_end)) %>% 
#   group_by(implant, animal, day_desc, is.pc, rew_at_end, line_id) %>%
#   dplyr::summarise(calc.ecdfs.summary(line_id, fraction.active, line_id[1]))


pooled.ecdf.df = fraction.approaches.cell.active %>% 
  left_join(trials.meta.df) %>%
  left_join(place.cell.db) %>%
  #filter(rew_at_end == 1) %>%
  #filter(day_desc == 'learning1 day#5') %>%
  #filter(day_desc == 'learning2 day#2') %>%
  mutate(line_id=paste(implant, animal, is.pc)) %>% 
  group_by(implant, animal, is.pc, line_id) %>%
  dplyr::summarise(calc.ecdfs.summary(line_id, fraction.active, line_id[1]))

pooled.ecdf.df.mean = pooled.ecdf.df %>%
  group_by(knot, implant, is.pc) %>%
  dplyr::summarise(val.mean = mean(mean.val), 
                   sem.val = sem(mean.val),
                   .groups='drop') %>%
  dplyr::rename(mean.val=val.mean)

print('Fraction of cells frequently active at reward')
pooled.ecdf.df.mean %>% filter(knot == 0.5) %>% dplyr::mutate(1-mean.val)

print('Fraction of cells not active at reward')
pooled.ecdf.df.mean %>% filter(knot == 0.1) 


pooled.ecdf.df %>%
  ggplot(aes(x=knot, y=mean.val, color=is.pc)) +
  geom_step(aes(group=line_id), alpha=0.5, size=0.4) +
  geom_step(data = pooled.ecdf.df.mean,
            alpha=0.8, size=0.8) +
  facet_grid(implant ~ .) +
  xlab('Approaches when cell active') +
  ylab('Cells CDF') +
  scale_color_manual(values=rev(side.two.coulours)) +
  scale_x_continuous(labels = scales::percent, breaks=c(0,0.5,1)) +
  scale_y_continuous(breaks=c(0,0.5,1)) +
  gtheme +
  theme(legend.position='none')
figure.ggsave('FigS3D-cdf-approaches-active.pdf',
              width=4.3,
              height=5.4)


# ecdf.df %>%
#   ggplot(aes(x=knot, y=mean.val, group=line_id)) +
#   geom_step(aes(color=is.pc)) +
#   facet_grid(implant ~ is.pc) +
#   xlab('Approaches when cell active') +
#   ylab('Cells CDF') +
#   scale_color_manual(values=rev(side.two.coulours)) +
#   scale_x_continuous(labels = scales::percent) +
#   gtheme


# ecdf.df %>%
#   ggplot(aes(x=fraction.active, group=line_id, color=is.pc)) +
#   stat_ecdf(geom='step') +
#   facet_grid(implant ~ is.pc) +
#   xlab('Approaches when cell active') +
#   ylab('Cells CDF') +
#   scale_color_manual(values=rev(side.two.coulours)) +
#   scale_x_continuous(labels = scales::percent) +
#   gtheme
```


```{r}
# average over cells in the trial
trial.rew.traces = all.rew.aligned.traces[,
                   .(mean.trace=mean(zscored_smooth_deconv_trace),
                     velocity=smooth_velocity[1],
                     #mean.trace=mean(log(0.1 + smoothed_deconv_trace)),
                     n=.N), 
                   by=.(implant, animal, date, trial_id, trial, is.rew.cell, timestamp_from_end)] 
data.table::setorder(trial.rew.traces, implant, animal, date, trial_id, trial, timestamp_from_end, is.rew.cell)
```


Change in velocity vs the activity of reward active cells
```{r}
# trial.rew.cells.traces = trial.rew.traces %>%
#   filter(is.rew.cell) %>%
#   filter(velocity < 50) %>%
#   arrange(implant, trial_id, animal, date, trial, timestamp_from_end) %>%
#   group_by(implant, trial_id, animal, date, trial) %>%
#   dplyr::mutate(acceleration = calc.acceleration(velocity, timebin.dur.msec)) %>%
#   ungroup()
# 
# rew.cells.traces.cor.line = trial.rew.cells.traces %>% 
#   filter(!is.na(mean.trace), !is.na(acceleration)) %>%
#   filter(timestamp_from_end <= 0, timestamp_from_end >= -5000) %>%
#   # group_by(implant, animal, date, trial_id) %>%
#   # dplyr::mutate(nvals = sum(!is.na(mean.trace))) %>%
#   # dplyr::ungroup() %>%
#   # dplyr::filter(nvals > 10) %>%
#   # dplyr::arrange(implant, animal, date, trial_id, timestamp_from_end) %>%
#   # dplyr::group_by(implant, animal, date, trial_id) %>%
#   #dplyr::summarise(cross.corr.vals.line(mean.trace, acceleration))
#   group_by(implant, animal, timestamp_from_end) %>%
#   dplyr::summarise(trace.mean=mean(mean.trace),
#                    velocity.mean=mean(velocity, na.rm=TRUE),
#                    acceleration.mean=mean(acceleration, na.rm=TRUE),
#                    .groups='drop') %>%
#   arrange(implant, animal, timestamp_from_end) %>%
#   group_by(implant, animal) %>%
#   dplyr::summarise(cross.corr.vals.line(trace.mean, acceleration.mean))
# 
# rew.cells.traces.cor.mean.line = rew.cells.traces.cor.line %>%
#   group_by(implant, lag.ms) %>%
#   dplyr::summarise(acf.mean=mean(acf), .groups='drop')
# 
# rew.cells.traces.cor.line %>%
#   mutate(animal_line=paste(implant, animal)) %>%
#   ggplot(aes(x=-lag.ms/1000, y=acf)) +
#   geom_line(aes(group=animal_line), color='#777777', size=0.2) +
#   geom_line(data=rew.cells.traces.cor.mean.line,
#            mapping=aes(y=acf.mean),
#            color='#333333', size=0.8) +
#   geom_vline(xintercept = 0, linetype='dashed', color='#333333') +
#   geom_hline(yintercept = 0, linetype='dashed', color='#333333') +
#   scale_x_continuous(breaks=seq(-0.4,0.4,0.4)) +
#   scale_y_continuous(breaks=seq(-1.0, 1.0, 0.5), limits=c(-0.8,0.8)) +
#   facet_grid(. ~ implant) +
#   xlab('Acceleration lag (s)') + ylab('Cross-correlation') +
#   gtheme
# figure.ggsave('FigureS4-deceleration-cor.pdf', width=5.0, height=3.6)
```


Difference between reward and other cells
```{r}
rew.traces.norm = trial.rew.traces %>%
  filter(!is.na(is.rew.cell)) %>%
  #filter(n >= 3) %>%
  pivot_wider(id_cols=c(implant, animal, date, trial_id, trial, timestamp_from_end),
              values_from='mean.trace', 
              names_from=is.rew.cell,
              names_prefix='rew.cell.') %>%
  mutate(trace.diff = rew.cell.TRUE - rew.cell.FALSE,
         trace.ratio = rew.cell.TRUE / rew.cell.FALSE,
         timestamp_from_end_bin = ceiling(timestamp_from_end / timebin.width))%>%
  filter(!is.na(trace.diff))

rew.traces.norm %>%
  group_by(implant, timestamp_from_end) %>%
  dplyr::summarise(mean.trace=mean(trace.diff, na.rm=TRUE), 
                     sem.trace=sem(trace.diff)) %>%
  ggplot(aes(x=timestamp_from_end/1000, y=mean.trace)) +
  geom_ribbon(aes(ymin=mean.trace-sem.trace, 
                  ymax=mean.trace+sem.trace),
                  fill='#888888') +
  scale_x_continuous(limits=c(-5, 5), breaks=seq(-4,4,2)) +
  scale_fill_manual(values=rev(side.two.coulours)) +
  facet_grid(. ~ implant) + xlab('Time to reward (s)') + 
  geom_hline(yintercept = 0, linetype='dashed', color='#333333') +
  ylab('activity z-score diff') +
  gtheme

figure.ggsave('Fig4E-approach_traces.pdf', width=6.0, height=3.9)

# Per animal
rew.traces.norm %>%
  #filter(implant=='vCA1') %>%
  dplyr::group_by(animal) %>%
  dplyr::mutate(ordinal = dplyr::cur_group_id()) %>%
  dplyr::group_by(implant, animal, ordinal, timestamp_from_end) %>%
  dplyr::summarise(mean.trace=mean(trace.diff, na.rm=TRUE), 
                   sem.trace=sem(trace.diff)) %>%
  #dplyr::mutate(ordinal = as.numeric(animal)) %>%
  ggplot(aes(x=timestamp_from_end/1000, y=ordinal, fill=mean.trace)) +
  #geom_ribbon(aes(ymin=mean.trace-sem.trace, 
  #                ymax=mean.trace+sem.trace),
  #                fill='#888888', alpha=0.2) +
  geom_tile(width=0.2) +
  xlab('Time (s)') +
  ylab('Approach') +
  scale_x_continuous(limits=c(-5, 5), breaks=seq(-4,4,2)) +
  facet_wrap(implant ~ ., scales = 'free_y') +
  gtheme +
  scale_fill_gradientn(colours = jet.colours(7)) 

figure.ggsave('FigureS4E-reward-diff.pdf', width=8, height=5)
#plotly::ggplotly()

rew.traces.norm %>%
  left_join(trials.meta.df) %>%
  ggplot() +
  geom_tile(aes(x=timestamp_from_end/1000, 
                y=as.integer(day_desc), 
                fill=trace.diff),
            width=0.2) +
  xlab('Time (s)') +
  ylab('Approach') +
  scale_x_continuous(limits=c(-5, 5), breaks=seq(-4,4,2)) +
  facet_wrap(implant ~ animal, scales = 'free_y') +
  gtheme +
  #theme(legend.position = 'none') +
  scale_fill_gradientn(colours = jet.colours(7)) + 
  scale_y_reverse()
```

```{r}
# average over cells in the trial in the timebin
bin.trial.rew.traces = as.data.table(rew.traces.norm)[timestamp_from_end_bin == 0 | timestamp_from_end_bin == -4,
            .(bin.activity=mean(trace.diff)), 
              #bin.activity=trace.diff[1]),
            by=.(implant, animal, date, trial_id, trial, timestamp_from_end_bin)] 

bin.trial.rew.traces$timestamp_from_end_bin = as.factor(bin.trial.rew.traces$timestamp_from_end_bin)
bin.trial.rew.traces$is_proximal = as.factor(bin.trial.rew.traces$timestamp_from_end_bin == 0)
bin.trial.rew.traces$aday = as.factor(
  paste(format(bin.trial.rew.traces$animal), 
        format(bin.trial.rew.traces$date), sep='_')) %>%
  as.integer() %>% as.factor()


bin.trial.rew.traces.wide = pivot_wider(
  bin.trial.rew.traces,
  id_cols=c(implant, animal, date, trial_id, trial, aday),
  values_from=bin.activity,
  names_from=is_proximal,
  names_prefix='is_proximal_') %>%
  mutate(trace.change=is_proximal_TRUE - is_proximal_FALSE)

compared.bin.trial.rew.traces = filter(bin.trial.rew.traces) %>% 
    mutate(val=log(2.0 + bin.activity)) %>% filter(!is.na(val), val < Inf)
printf('N approaches = ')
compared.bin.trial.rew.traces %>%
  ungroup() %>%
  dplyr::select(implant, animal, trial_id) %>%
  dplyr::distinct() %>%
  dplyr::count(implant)  

m.rew.activ.diff = lmer.test.print(
  bin.trial.rew.traces,
  val,
  diagnostics.groupvar = animal,
  fixed.effects = implant * is_proximal,
  randef.str = '(1 | aday)')
pairwise.post.hoc(m.rew.activ.diff, factor.interaction = 'implant:is_proximal')

models = create.bayes.lm.pair(
  filter(bin.trial.rew.traces, implant=='vCA1'),
  formula.full = val ~ 1 + is_proximal + aday,
  formula.null = val ~ 1 + aday,
  whichRandom = c('aday'),
  iterations = 10000
)
models$full / models$null
calc.pair.95CI(models$full, function(x) exp(x) - 1, show.percent.change = FALSE,
               pair.vars = c('is_proximal-FALSE', 'is_proximal-TRUE'))

```


```{r}
mean.rew.traces %>%
  ggplot(aes(x=timestamp_from_end/1000, y=mean.trace)) +
  geom_ribbon(aes(ymin=mean.trace-sem.trace, 
                  ymax=mean.trace+sem.trace, 
                  fill=is.rew.cell),
              alpha=0.75) +
  xlim(c(-5,5)) +
  scale_fill_manual(values=rev(side.two.coulours)) +
  facet_grid(. ~ implant) + xlab('Time (s)') +ylab('Population z-score') +
  gtheme
figure.ggsave('FigS4B-approach_trace.pdf', width=8.4, height=3.9)
```

```{r}
all.rew.aligned.traces.per.cell.group = all.rew.aligned.traces.comparison[,
   .(bin.activity=mean(zscored_smooth_deconv_trace),
     ntrials=length(unique(trial_id))),
   by=.(animal, date, is.rew.cell, cell_id, timestamp_from_end_bin)
 ][mouse.meta.df, on='animal']
all.rew.aligned.traces.per.cell.group$timestamp_from_end_bin = 
  as.factor(all.rew.aligned.traces.per.cell.group$timestamp_from_end_bin)
all.rew.aligned.traces.per.cell.group$aday = as.factor(
  paste(format(all.rew.aligned.traces.per.cell.group$animal), 
        format(all.rew.aligned.traces.per.cell.group$date), sep='_')) %>%
  as.integer() %>% as.factor()
all.rew.aligned.traces.per.cell.group$is.rew.cell = as.factor(all.rew.aligned.traces.per.cell.group$is.rew.cell)
```


```{r}
all.rew.aligned.traces.per.cell.group %>%
  filter(timestamp_from_end_bin == 0) %>%
  ggplot(aes(x=is.rew.cell, y=bin.activity)) +
  geom_hline(yintercept = 0, linetype='dashed', color='#333333') +
  geom_violin(aes(fill=is.rew.cell, color=is.rew.cell)) +
  geom_jitter(width=0.35, height=0.0, size=0.1, shape=1, alpha=0.2, color='#333333') +
    stat_summary(fun=mean, geom="point", shape=23, size=2, color='white') +
  scale_fill_manual(values=rev(side.two.coulours)) +
  scale_color_manual(values=rev(side.two.coulours)) +
  facet_grid(. ~ implant) +
  ylim(c(-0.5, 4.0)) +
  ylab('z-scored F') +
  gtheme
  
figure.ggsave('FigS4C-approach_traces_stats.pdf', width=7.4, height=4.1)
```

```{r}
implant.loc = 'dCA1'

m.pc.proximal = lmer.test.print(
  subset(all.rew.aligned.traces.per.cell.group, implant==implant.loc & timestamp_from_end_bin==0),
  log(2.0 + bin.activity),
  diagnostics.groupvar = is.rew.cell,
  fixed.effects = is.rew.cell,
  randef.str = '(1 + date | animal)')

models = create.bayes.lm.pair(
  subset(all.rew.aligned.traces.per.cell.group, implant==implant.loc & timestamp_from_end_bin==0) %>%
    mutate(val=log(2.0 + bin.activity)),
  formula.full = val ~ 1 + is.rew.cell + aday,
  formula.null = val ~ 1 + aday,
  whichRandom = c('aday'),
  iterations = 10000
)
models$full / models$null
calc.pair.95CI(models$full, function(x) exp(x) - 1, show.percent.change = FALSE,
               pair.vars = c('is.rew.cell-FALSE', 'is.rew.cell-TRUE'))

group_by(subset(all.rew.aligned.traces.per.cell.group, implant==implant.loc), 
         is.rew.cell, timestamp_from_end_bin) %>%                
  dplyr::summarise(mean(bin.activity), sem(bin.activity), n())
```

