---
title: "R Notebook"
output: html_notebook
---


```{r setup}
library(dplyr)
library(plyr)
library(pracma)
library(readr)
library(tidyr)
library(stringr)
library(DT)
library(data.table)
library(tictoc)
library(datatrace)
library(foreach)
library(doSNOW)

# Plotting
library(ggplot2)
library(cowplot)

summarise = dplyr::summarise
summarize = dplyr::summarize

source('distances.R')
source('fixed_effects.R')
source('locations.R')
source('plotting_params.R')
source('place_field_utils.R')
source('utils.R')

perc2dist = 1.2
goal.cell.max.dist = 20 / perc2dist

load('data/downsampled_place_field_stats.RData')
```

# Stats on multifields
```{r}
source('place_field_utils.R')

down.peaks.dist = bind_rows(
  mutate(down.habit.si, exp_title = '1_habituation') %>% dplyr::select(-date) %>% dplyr::rename(date=date.test),
  mutate(down.test.si, exp_title = '2_test')
) %>%
  left_join(trials.meta.df) %>%
  left_join(mouse.meta.df)
```

Plot distribution of distance to reward 
```{r}
down.peaks.dist %>%
  filter(signif.si) %>%
  dplyr::mutate(animal_beforetest_day = paste(animal, day_desc, sep='_')) %>%
  ggplot() +
  geom_density(aes(x=min.rew.dist * perc2dist, 
                   #linetype=exp_title, 
                   fill=exp_title), 
               alpha=0.3,
               adjust=1,
               color='#333333') +
               #adjust=1/2) +
  facet_grid(. ~ implant) +
  geom_vline(xintercept = goal.cell.max.dist * perc2dist, linetype='dotted') +
  coord_flip() +
  scale_linetype_manual(values=c("dashed", "solid"))+
  gtheme +
  xlim(c(0,100))+
  scale_fill_manual(values=c('#999999', '#0098ff')) +
  xlab('Distance (cm)') + ylab('Density') +
  ggtitle('Field distance from reward in downsampled data')

figure.ggsave('FigS2A-downsampled_reward_dist.pdf', height=6, width=8)
```

```{r}
summarize.downrew.pc.pct = function(df, dist.var=min.rew.dist, dist.threshold) {
  dist.var = enquo(dist.var)
  df %>%
    group_by(date, day_desc, animal, implant, exp_title) %>%
    dplyr::summarise(at.reward=sum((!!dist.var <= dist.threshold) & signif.si),
                     mean.cells = n() / max(shuffle_i),
                     npcs = sum(signif.si),
                     pct.pcs = npcs / n() * 100,
                     mean.pcs = npcs / max(shuffle_i),
                     pct.reward=at.reward / npcs * 100) %>%
    dplyr::select(-npcs, -at.reward)
}

peaks.summary.df = summarize.downrew.pc.pct(down.peaks.dist, dist.threshold=goal.cell.max.dist) %>%
  dplyr::mutate(animal_beforetest_day = paste(animal, day_desc, sep='_')) %>%
  filter(pct.pcs > 0) %>% 
  dplyr::ungroup()

peaks.summary.df$exp_title = as.factor(peaks.summary.df$exp_title)

print('Fraction of dCA1 place cells at reward increased')
fem.model = lmerTest::lmer(pct.reward ~ exp_title*implant + (1 + exp_title + day_desc | animal), 
                           data=peaks.summary.df, REML = TRUE)
plot.model.diagnostics(fem.model, peaks.summary.df$implant, peaks.summary.df$exp_title)
anova(fem.model, refit=FALSE, ddf='Satterthwaite')
pairwise.post.hoc(fem.model, factor.interaction=c('exp_title:implant'))
create.summary(peaks.summary.df, pct.reward, implant, exp_title)

peaks.summary.df$aday = as.factor(peaks.summary.df$animal_beforetest_day) %>% as.integer %>% as.factor
peaks.summary.df$animal = as.factor(peaks.summary.df$animal)

# dCA1 BF
dca1.rew.pc.pct = filter(peaks.summary.df, implant == 'dCA1')
models = create.bayes.lm.pair(dca1.rew.pc.pct, 
                              formula.full = pct.reward ~ 1 + exp_title + aday + animal,
                              formula.null = pct.reward ~ 1 + aday + animal,
                              whichRandom = c('aday', 'animal'),
                              iterations=10000)
models$full / models$null
calc.pair.95CI(models$full, pair.vars = c('exp_title-1_habituation', 'exp_title-2_test'))

# vCA1 BF
vca1.rew.pc.pct = filter(peaks.summary.df, implant == 'vCA1')
models = create.bayes.lm.pair(vca1.rew.pc.pct, 
                              formula.full = pct.reward ~ 1 + exp_title + aday + animal,
                              formula.null = pct.reward ~ 1 + aday + animal,
                              whichRandom = c('aday', 'animal'),
                              iterations=10000)
models$full / models$null
calc.pair.95CI(models$full, pair.vars = c('exp_title-1_habituation', 'exp_title-2_test'))

animal.peaks.summary.df = peaks.summary.df %>%
  group_by(implant, animal, exp_title) %>%
  dplyr::summarise(pct.reward.mean = mean(pct.reward),
                   n=n())
peaks.summary.df %>%
  ggplot(aes(x=exp_title, y=pct.reward, group=animal_beforetest_day)) +
  geom_line(size=0.25, color='#888888') +
  geom_line(data=animal.peaks.summary.df, 
          mapping=aes(y=pct.reward.mean, group=animal),
          size=0.5, color='#333333') +
  facet_grid(. ~ implant, scales = 'free') +
  xlab('') +
  gtheme +
  ylab('Place cells at reward (%)') +
  ggtitle('Fraction of fields at reward increased at test trial')

figure.ggsave('FigS2B-downsampled_reward_dist_stat.pdf',
       height=5.3, width=6)
```

Change in the field size
```{r}
summarize.shuffle = function(df) {
  df %>%
    dplyr::select(date, day_desc, animal, implant, exp, exp_title, cell_id, 
                  field.size.50, signif.si, field.max, field.mean, npeaks.at.rew, min.rew.dist) %>%
    group_by(date, day_desc, animal, implant, exp, exp_title, cell_id) %>%
    dplyr::summarise(across(.fns=~ mean(.x, na.rm=TRUE)),
                     .groups='drop')
}
down.peaks.shuffle.mean = summarize.shuffle(down.peaks.dist) 
```

```{r}
down.peaks.shuffle.mean.pcs = down.peaks.shuffle.mean %>%
  filter(signif.si > 0.5) %>%
  mutate(field.size = field.size.50 / nbins/nbins * 100,
         aday = paste(animal, format(date), sep='_'))
down.peaks.shuffle.mean.pcs$aday = as.factor(down.peaks.shuffle.mean.pcs$aday) %>% as.integer() %>% as.factor()

down.peaks.shuffle.mean.pcs %>%
  ggplot(aes(x=exp_title, y=field.size)) +
  geom_violin(fill=single.colour, color=single.colour) +
  geom_violin(fill='transparent', colour='white', draw_quantiles=0.5, size=1) +
  geom_jitter(shape=16, width=0.4, height=0, size=0.5, alpha=0.15, color='#333333') +
  facet_grid(. ~ implant) +
  xlab('') + ylab('% of maze') +
  gtheme

down.peaks.shuffle.mean.pcs %>%
  ggplot() +
  geom_density(aes(x=field.size, 
                   fill=exp_title), 
               alpha=0.3,
               adjust=1,
               color='#333333') +
  facet_grid(. ~ implant) +
  coord_flip() +
  scale_linetype_manual(values=c("dashed", "solid"))+
  gtheme +
  xlim(c(0,20))+
  scale_fill_manual(values=c('#999999', '#0098ff')) +
  xlab('Field size (% of maze)') + ylab('Density')
```

```{r}
lmer.test.print(
  df = filter(down.peaks.shuffle.mean.pcs, implant=='vCA1'),
  var = log(field.size),
  fixed.effects = exp_title,
  randef.str = '(1 + day_desc | animal)',
  diagnostics.groupvar = exp_title)

models = create.bayes.lm.pair(
  filter(down.peaks.shuffle.mean.pcs, implant=='vCA1') %>% mutate(val=log(field.size)),
  formula.full = val ~ 1 + aday + exp_title,
  formula.null = val ~ 1 + aday)
models$full/models$null
calc.pair.95CI(models$full, ytransform = function(x) {exp(x) * 100}, 
               pair.vars = c('exp_title-1_habituation', 'exp_title-2_test'),
               show.percent.change = TRUE)
  
```



