---
title: "R Notebook"
output: html_notebook
---


```{r setup} 
library(dplyr)
library(plyr)
library(pracma)
library(readr)
library(tidyr)
library(tibble)
library(stringr)
library(DT)
library(data.table)
library(datatrace)

library(ggplot2)
library(cowplot)
gtheme = theme_minimal() + theme_cowplot() +
  theme(text = element_text(size=18), axis.text = element_text(size=15))

summarise = dplyr::summarise
summarize = dplyr::summarize
```

Setup example variables
```{r}
nbins = 20
animal_name = 'F-TL'
exp_title='learning'
day = '2019-09-06'
cell_name = 256
```



```{r}
geom_rewards = function(rewards.df, subject=NULL, day=NULL, nbins=20) {
  dayreward.df = rewards.df
  if (!is.null(subject)) {
    dayreward.df = filter(rewards.df, animal==subject)
  }
  if (!is.null(day)) {
    dayreward.df = filter(dayreward.df, date==day)
  }
  rew.col = 'black'
  #rew.shape = 0
  rew.shape = 2
  rew.size = 2
  bin.size = ceil(100 / nbins)
  geom_point(data=dayreward.df, aes(x=trans_x / bin.size, y=(100 - trans_y) / bin.size), 
             shape=rew.shape,
             color=rew.col, 
             size=rew.size,
             stroke=2,
             alpha=0.8)
}

all.locations.df = map_dfr(rootdirs, read_locations)
rewards.df =  all.locations.df %>%
  filter(!is_test) %>%
  dplyr::rename(animal=Animal) %>%
  left_join(mouse.meta.df, by='animal') %>% 
  left_join(trials.meta.df, by=c('date', 'animal', 'location_set'))
```

```{r}

f1 = odd.fields[[animal_name]][[day]][[paste(cell_name)]]
oc1 = odd.occupancies[[animal_name]][[day]][[paste(cell_name)]]

f2 = even.fields[[animal_name]][[day]][[paste(cell_name)]]
oc2 = even.occupancies[[animal_name]][[day]][[paste(cell_name)]]
odd.field = create.pf.df(f1, oc1)
even.field = create.pf.df(f2, oc2)

oddeven.cor = field.cor(odd.field, even.field, make.cor.plot=TRUE, max.xy=nbins)
cor.title = paste0('Odd vs Even cor=', format(oddeven.cor$cor, digits=2))
oddeven.cor$g + labs(title=cor.title, fill='Correlation')

```


```{r}

plot.field.comparison = function(animal_name, day, cell_name, plot.dir=NA) {
  odd.pf = create.partial.df(odd.fields, odd.occupancies, animal_name, day, cell_name, 'Odd')
  even.pf = create.partial.df(even.fields, even.occupancies, animal_name, day, cell_name, 'Even')
  early.pf = create.partial.df(early.fields, early.occupancies, animal_name, day, cell_name, 'Early')
  late.pf = create.partial.df(late.fields, late.occupancies,  animal_name, day, cell_name, 'Late')
  
  cell.row = run.trials.pc %>% filter(animal==animal_name, date==day, cell_id==cell_name)
  
  text.theme = theme(text = element_text(size=10),
                     plot.title = element_text(size=10))
  
  g.placefield = bind_rows(odd.pf, even.pf, early.pf, late.pf) %>%
    plot.pf(max.x=nbins, max.y=nbins) +
    facet_wrap(. ~ group, ncol = 2) +
    geom_rewards(rewards.df, animal_name, day) +
    labs(title=paste0(animal_name,
                      ', ', day,
                      ', cell ', cell_name, 
                      '\nSI = ', format(cell.row$spatial.information, digits=2), ' bits/s',
                      ifelse(cell.row$signif.si, ' *', ''),
                      ', ', format(cell.row$spatial.information.perspike, digits=2), ' bits/spike',
                      '\nMI - bias = ', format(cell.row$mutual.info - cell.row$mutual.info.bias, digits=3),
                      ifelse(cell.row$signif.mi, '*', ''),
                      '\nsparsity = ', format(cell.row$sparsity, digits=2)),
         fill='Deconv\ntrace') +
    text.theme

  
  oddeven.cor = field.cor(odd.pf, even.pf, make.cor.plot=TRUE, max.xy=nbins)
  cor.title = paste0('cor=', format(oddeven.cor$cor, digits=2))
  g.oddeven.cor = oddeven.cor$g + labs(title=cor.title, fill='') + 
    geom_rewards(rewards.df, animal_name, day) + text.theme
  
  earlylate.cor = field.cor(early.pf, late.pf, make.cor.plot=TRUE, max.xy=nbins)
  cor.title = paste0('cor=', format(earlylate.cor$cor, digits=2))
  g.earlylate.cor = earlylate.cor$g + labs(title=cor.title, fill='') + 
    geom_rewards(rewards.df, animal_name, day) + text.theme +
    theme(legend.position='none')
  
  g.cors = plot_grid(g.earlylate.cor, g.oddeven.cor, ncol=2, rel_widths=c(1, 1.7))
  
  g = plot_grid(g.placefield, g.cors, ncol=1, rel_heights=c(2,1))
  if (!is.na(plot.dir)) {
    if (cell.row$is.pc) {
      plot.subdir = file.path(plot.dir, 'place_cell')
    } else if (cell.row$is.pc) {
      plot.subdir = file.path(plot.dir, 'signif')
    } else {
      plot.subdir = file.path(plot.dir, 'other')
    }
    dir.create(plot.subdir, recursive=TRUE)
    fname = paste0('place_field_cell_', cell_name, '.jpg')
    ggsave(file.path(plot.subdir, fname), 
           g,
           width=5.5, height=8, units='cm', dpi=300)
  }
  return(g)
}
```


```{r}
plot.dir = file.path('/tmp/pf_stability/', animal_name, day)
plot.field.comparison(animal_name, day, cell_name, plot.dir=plot.dir)
```

```{r}
save.field.comparison = function(animal_name, day, cell_name) {
  plot.dir = file.path('/mnt/DATA/Prez/pf-daystability', animal_name, day)
  plot.field.comparison(animal_name, day, cell_name, plot.dir)
  return(1)
}

run.trials.si %>%
  select(animal, date, cell_id) %>%
  distinct() -> tmp.df

for (i in 1:nrow(tmp.df)) {
   tryCatch({save.field.comparison(tmp.df$animal[i],
                                   tmp.df$date[i],
                                   tmp.df$cell_id[i])},
  error=function(e){cat("ERROR for row i=", num2str(i), ":",conditionMessage(e), "\n")})
}
```

# Place field for each trial separately

Load the traces
```{r}
animal_name = 'D-BR'
exp_title='learning'
day = '2019-07-28'
root_dir = '/mnt/DATA/Prez/cheeseboard-down/down_2/2019-07/'
#cell_name = 47


caimg_result_dir = file.path(root_dir, exp_title, day, 'caiman', animal_name, 'filtered/')
data.traces = read.data.trace(caimg_result_dir, filter_exp_title='trial')
setorder(data.traces, trial_id, cell_id, timestamp)
data.traces$is_running = isRunning(data.traces, 2, 4, 500)
data.traces = as.data.table(data.traces)
data.traces.run = data.traces[(is_running), ]
detect.events(data.traces.run, deconv.threshold=0.3)

```

```{r}
frame.rate = 1000 / 200

plot.cell.trials = function(cell.df, trace.var='trace') {
  if (nrow(cell.df) == 0) {
    return(ggplot(data.frame()))
  }
  animal_name = cell.df$animal[1]
  day = cell.df$date[1]
  trials = unique(cell.df$trial)
  
  trials.spatial = c()
  all.pf.df = data.frame()
  for (trial_no in trials) {
    pf = cell.spatial.info(cell.df[trial == trial_no, ],
                           nbins, nbins,
                           trace.var = trace.var,
                           generate.plots=FALSE,
                           nshuffles=0,
                           min.occupancy = 1)
    pf.df = create.pf.df(pf$field, pf$occupancy, 
                         frame.rate=frame.rate,
                         min.occupancy.sec = 0.1)
    pf.df$trial = num2str(trial_no, fmt=0)
    all.pf.df = bind_rows(all.pf.df, pf.df)
  }
  
  pf = cell.spatial.info(cell.df,
                         nbins, nbins,
                         trace.var = trace.var,
                         generate.plots=FALSE,
                         nshuffles=100)
  pf.df = create.pf.df(pf$field, pf$occupancy, 
                       frame.rate=frame.rate)
  pf.df$trial = 'all'
  all.pf.df = bind_rows(all.pf.df, pf.df)
  
  cell_info = pf$cell_info
  g = plot.pf(all.pf.df, max.x=nbins, max.y=nbins) +
    geom_rewards(rewards.df, animal_name, day, nbins) +
    facet_wrap(. ~  trial, ncol=3) +
    labs(fill=paste(trace.var, 'values'),
         title=paste0(format(day), ' ', animal_name, ' Cell ', cell_name, 
                      '\nSI = ', format(cell_info$spatial.information, digits=2),
                      ifelse(cell_info$signif.si, '*', ''),
                      ' SI per spike = ', format(cell_info$spatial.information.perspike, digits=2),
                      '\nMI - bias = ', format(cell_info$mutual.info - cell_info$mutual.info.bias, digits=3),
                      ifelse(cell_info$signif.mi, '*', '')))
  
  
  print(pf$cell_info$spatial.information)
  print(pf$cell_info$mutual.info)
  print(pf$cell_info$mfr)
  return(g)
}

cell_name = 34
cell.df = data.traces.run[cell_id == cell_name & x >= 0 & y >= 0, ]
binned.cell.df = bin.time.space(cell.df, 
                                nbins.x = nbins,
                                nbins.y = nbins,
                                get.bin.thresholds.fun=get.quantiles.fun(c(0.2, 0.95, 1.0)),
                                binned.var='deconv_trace',
                                timebin.dur.msec=200)
binned.cell.df[,is_running:=as.logical(is_running)]

plot.cell.trials(binned.cell.df, trace.var='deconv_trace')

plot.event.vectors(binned.cell.df, event.var=nevents, event.thr=1) +
  geom_path(data=binned.cell.df, mapping=aes(x=x,y=100-y,group=trial_id), alpha=0.6) +
  geom_rewards(rewards.df, animal_name, day, 100) +
  facet_wrap(. ~ trial, nrow = 3)

plot.trace.events(binned.cell.df, event.var=nevents, event.thr=1) +
  geom_rewards(rewards.df, animal_name, day, 100)
```

# Changes in PF over days
```{r}
#selected.days = c('2019-08-29', '2019-08-30', '2019-09-03', '2019-09-04', '2019-09-06','2019-09-07', '2019-09-08')
#all.days = place.cell.db$date %>% unique
#all.days = goal.cell.db$day_desc %>% unique
#selected.days = format(all.days)

trials.meta.df = data.table(trials.meta.df)
create.selected.pf.df = function(animal_name, cell_name) {
  selected.days = names(run.fields[[animal_name]])
  day_descs = map_chr(selected.days, ~ trials.meta.df[date==.x & animal == animal_name, day_desc][1])
  data.frame(animal=animal_name,
             cell_id=format(cell_name),
             day=selected.days,
             day_desc = day_descs)  
}

rowwise.partial.df = function(row) {
  animal_name = as.character(row$animal)
  cell_name = format(row$cell_id)
  day = format(row$day)
  
  field = run.fields[[animal_name]][[day]][[cell_name]]
  if (is.null(field)) {
    #print(paste('Field not found for', animal_name, day, cell_name))
    return(data.frame())
  }
  df = create.pf.df(field,
                    run.occupancies[[animal_name]][[day]][[cell_name]])

  df$animal = animal_name
  df$cell_id = cell_name
  return(df)
}

goal.cell.db = data.table(goal.cell.db)


rowwise.cell.desc = function(row) {
  animal_name = as.character(row$animal)
  cell_name = format(row$cell_id)
  day = format(row$day)
  goal.db.row = goal.cell.db[animal==animal_name & cell_id==cell_name & date==day,]
  row$desc = 'NI'
  if (nrow(goal.db.row) > 0) {
    row$desc = paste0(ifelse(goal.db.row$is.pc, 'PC ', 'NPC'), ifelse(goal.db.row$is.goal.cell, ' & GC', ''))
  }
  row
}

plot.all.day.fields = function(animal_name, cell_id) {
  selected.cells.df = create.selected.pf.df(animal_name, cell_id)
  pf = selected.cells.df %>%
    adply(.margins=1, .fun=rowwise.partial.df) %>%
    dplyr::rename(date=day)
  
  cell.desc.df = selected.cells.df %>%
    adply(.margins=1, .fun=rowwise.cell.desc) %>%
    dplyr::rename(date=day)
  
  plot.pf(pf, max.x=nbins, max.y=nbins) +
    facet_wrap(. ~ day_desc, ncol=3) +
    geom_text(data=cell.desc.df, mapping=aes(x=1, y=nbins - 2, label=desc), size=3, hjust=0)+
    geom_rewards(rewards.df, animal_name) 
}

plot.all.day.fields('D-BR', 3)
```

Save place fields for all days
```{r}
animal.cells.df = goal.cell.db %>%
  select(animal, cell_id) %>% 
  dplyr::distinct()

plot.rootdir = "/mnt/DATA/Prez/pf-shuffled/"
for (i in 1:nrow(animal.cells.df)) {
  row = animal.cells.df[i, ]
  animal_name = as.character(row$animal)
  cell_name = format(row$cell_id)
  g = plot.all.day.fields(animal_name, cell_name) +
    labs(title = paste(animal_name, cell_name))
  plot.dir = file.path(plot.rootdir, animal_name)
  if (!file.exists(plot.dir)) {
    dir.create(plot.dir, recursive=TRUE)
  }
  ggsave(file.path(plot.dir, paste0(row$cell_id, '.jpg')),
         g, width=10, height=12, units='cm')
}
```

## Plot event vectors
```{r}
animal_name = 'F-TL'
exp_title = 'beforetest'

animal.caimg_dirs = Filter(
  function(caimg_dir) {
    str_detect(caimg_dir, animal_name) & str_detect(caimg_dir, 'learning')
  },
  caimg_result_dirs)

paths.df = data.frame()
binned.events = data.frame()
for (caimg_dir in animal.caimg_dirs) {
  data.traces = read.data.trace(caimg_dir, filter_exp_title=exp_title)
  if (nrow(data.traces) > 0) {
    setorder(data.traces, trial_id, cell_id, timestamp)
    detect.events(data.traces, deconv.threshold=0.3, minpeakdistance=10)
    data.traces$is_running = as.logical(isRunning(data.traces, 2, 4, 500))
    binned.traces = bin.time.space(data.traces, 
                                   nbins.x = nbins,
                                   nbins.y = nbins,
                                   get.bin.thresholds.fun=get.quantiles.fun(c(0.2, 0.95, 1.0)),
                                   binned.var='deconv_trace',
                                   timebin.dur.msec=200)
    
    binned.events = bind_rows(binned.events, binned.traces[nevents >= 0.2, ])
    
    cell_name = binned.traces$cell_id[1]
    paths.df = bind_rows(paths.df, binned.traces[cell_id==cell_name, ])
  }
}
```

```{r}
binned.events = left_join(binned.events, trials.meta.df)
paths.df = left_join(paths.df, trials.meta.df)

binned.events = data.table(binned.events)
paths.df = data.table(paths.df)
plot.dir = file.path('/mnt/DATA/Prez/cheeseboard-events', animal_name, exp_title)
if (!file.exists(plot.dir)) {
  dir.create(plot.dir, recursive=TRUE)
}
for (cell_name in unique(binned.events$cell_id)) {
  cell.events.df = binned.events[cell_id==cell_name, ]
  g = plot.event.vectors(cell.events.df) +
    geom_path(data=paths.df, mapping=aes(x=x, y=100-y, group=trial_id), alpha=0.2) +
    geom_rewards(rewards.df, animal_name, nbins=100) +
    facet_wrap(day_desc ~ .)
  ggsave(file.path(plot.dir, paste0(cell_name, '.jpg')),
       g, width=16, height=13, units='cm')
}
```


# Population activity across space
```{r}
animal_name = 'G-BR'
exp_title='learning'
day = '2020-01-31'
root_dir = '/mnt/DATA/Prez/cheeseboard-down/down_2/2020-01'
#cell_name = 47

caimg_result_dir = file.path(root_dir, exp_title, day, 'caiman', animal_name, 'filtered/')
data.traces = read.data.trace(caimg_result_dir, filter_exp_title='trial')
setorder(data.traces, trial_id, cell_id, timestamp)
detect.events(data.traces, deconv.threshold=0.2)

```

```{r}
binned.traces = bin.time.space(data.traces, 
                               nbins.x = nbins,
                               nbins.y = nbins,
                               get.bin.thresholds.fun=get.quantiles.fun(c(0.2, 0.95, 1.0)),
                               binned.var='deconv_trace',
                               timebin.dur.msec=200)

all.pf.df = data.frame()

for (trial_no in unique(binned.traces$trial)) {
  pf = cell.spatial.info(binned.traces[trial == trial_no, ],
                         nbins, nbins,
                         trace.var = 'deconv_trace',
                         generate.plots=FALSE,
                         nshuffles=0,
                         min.occupancy = 1)
  pf.df = create.pf.df(pf$field, pf$occupancy, 
                       frame.rate=frame.rate,
                       min.occupancy.sec = 0.1)
  pf.df$trial = trial_no
  all.pf.df = bind_rows(all.pf.df, pf.df)
}
plot.pf(all.pf.df, max.x=nbins, max.y=nbins) +
  geom_rewards(rewards.df, animal_name, day, nbins) +
  facet_wrap(. ~ trial)
```

# Population activity across days for all mice
```{r}
all.pf.df = data.frame()
for (caimg_result_dir in caimg_result_dirs) {
  data.traces = read.data.trace(caimg_result_dir, filter_exp_title='trial')
  setorder(data.traces, trial_id, cell_id, timestamp)
  
  data.traces.immobile = data.traces[velocity <= 2.5, ]
  #detect.events(data.traces, deconv.threshold=0.2)
  data.traces.immobile$is.event = 0
  binned.traces = bin.time.space(data.traces.immobile, 
                                 nbins.x = nbins,
                                 nbins.y = nbins,
                                 get.bin.thresholds.fun=get.quantiles.fun(c(0.95, 1.0)),
                                 timebin.dur.msec=200)
  
  pf = cell.spatial.info(binned.traces,
                         nbins, nbins,
                         trace.var = 'deconv_trace',
                         generate.plots=FALSE,
                         nshuffles=0,
                         min.occupancy = 1)
  pf.df = create.pf.df(pf$field, pf$occupancy, 
                       frame.rate=5,
                       min.occupancy.sec = 1)
  pf.df$animal = data.traces$animal[1]
  pf.df$date = data.traces$date[1]
  all.pf.df = bind_rows(all.pf.df, pf.df)
}
```

```{r}
g = plot.pf(all.pf.df, max.x=nbins, max.y=nbins) +
  geom_rewards(rewards.df, nbins=nbins) +
  facet_wrap(date ~ animal) +
  scale_fill_gradientn(limits=c(0, 0.3), colours=jet.colours(7))

ggsave('/tmp/all_fields_immobile.png', g, width=20, height=20, units='cm')
g
```

