---
title: "R Notebook"
output: html_notebook
---

```{r}
source('utils.R')
```



```{r}
xybins = 20
run.threshold = 2

prepare.traces = function(data.traces, 
                          quantile.fractions = c(0.95, 1.0),
                          binned.var='trace') {
  setorder(data.traces, trial_id, cell_id, timestamp)
  detect.events(data.traces, deconv.threshold=0.1)
  
  running.index = isRunning(data.traces, 2, 4, 500) 
  data.traces.run = data.traces[which(running.index), ]

  date_str = data.traces$date[1]
  animal_name = data.traces$animal[1]
  ## Keep only place cells or daystable cells
  #pc.cells = subset(place.cell.db, animal==animal_name & date==date_str & is.pc)$cell_id
  #stable.cells = subset(stable.cell.db, animal==animal_name & dateq==date_str & is.stable)$cell_id
  #data.traces.filtered = data.traces.run[cell_id %in% stable.cells, ]
  data.traces.filtered = data.traces.run
  binned.traces = bin.time.space(data.traces.filtered, 
                                 xybins, xybins,
                                 quantile.fractions,
                                 binned.var=binned.var,
                                 timebin.dur.msec=200)
  
  setorder(binned.traces, time_bin, cell_id)
  setkey(binned.traces, time_bin, cell_id)

  return(binned.traces)
}

eval.parts = lapply(caimg_result_dirs, function(caimg_result_dir) {
  data.traces = read.data.trace(caimg_result_dir, filter_exp_title = 'trial')
  quantile.fractions = c(0.95, 1.0)
  binned.traces = prepare.traces(data.traces, quantile.fractions, binned.var='trace')
  if (nrow(binned.traces) == 0) {
    return(data.frame())
  } else {
    print('Started evaluating the model')
    # binned.traces2 = binned.traces[!is.na(angle),]
    # nangles = 360/30
    # binned.traces2 = stimbin.traces(binned.traces2, angle, 30) %>%
    #  mutate(bin.angle = pmin(nangles, bin.angle + 7))
    # eval.df = eval.decoder(binned.traces2, 
    #                        train.fun=create.mfr.bayes,
    #                        predict.fun=bayesmax_mfr,
    #                        value.var=nevents,
    #                        stim.var=bin.angle,
    #                        nstim.bins=nangles,
    #                        error.fun = function(x,y) {min((x-y) %% nangles, (y-x) %% nangles)},
    #                        cv=TRUE,
    #                        min.samples=10)
    eval.df = eval.decoder(binned.traces,
                           nstim.bins=xybins*xybins,
                           error.fun=bin.distance.error(xybins, xybins),
                           train.fun=create.discrete.bayes,
                           predict.fun=bayesmax,
                           value.var=response_bin,
                           stim.var=bin.xy,
                           cv=TRUE,
                           min.samples=10)

    # eval.df = eval.decoder(binned.traces,
    #                        nstim.bins=xybins*xybins,
    #                        error.fun=bin.distance.error(xybins, xybins),
    #                        train.fun=create.mfr.bayes,
    #                        predict.fun=bayesmax_mfr,
    #                        value.var=nevents,
    #                        stim.var=bin.xy,
    #                        cv=FALSE,
    #                        min.samples=20)
    if (nrow(eval.df) > 0) {
      eval.df$animal = binned.traces$animal[1]
      eval.df$date = binned.traces$date[1]
    }
    toc()
    
    eval.df
  }
})

decoding.df = do.call('rbind', eval.parts)

mouse.meta.df = read.mouse.meta(rootdirs)
trials.meta.df = read.trials.meta(rootdirs)

decoding.joined = decoding.df %>%
  left_join(mouse.meta.df, by='animal') %>%
  left_join(trials.meta.df, by=c("animal", "date"))

decoding.joined$day_desc = as.factor(decoding.joined$day_desc)

summary(subset(decoding.joined, implant=='vCA1')$error)
summary(subset(decoding.joined, implant=='dCA1')$error)
summary(decoding.df$random_error)
```

Errors vary between days and mice. Show median error per animal per day:
```{r}
 data.table(decoding.df)[,.(med.error=median(error), .N), by=c('animal','date')][,median(med.error), by='animal']#[,med.error] %>% summary
```

```{r}
eval.summary = decoding.joined %>%
  group_by(date, day_desc, animal) %>%
  dplyr::summarise(mean.error=mean(error),
                   median.error=median(error),
                   sd.error=sd(error),
                   sem.error=sem(error))

ggplot(eval.summary, aes(x=day_desc, y=median.error, group=animal, color=animal)) +
  #geom_point() +
  geom_errorbar(aes(ymin=median.error-sem.error, ymax=median.error+sem.error), width=0.2) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

Eval on the next day
```{r}
otherday.decoding.df = data.frame()
quantile.fractions = c(0.95, 1.0)

models = list()
dates = rep('', length(caimg_result_dirs))
animal_names = rep('', length(caimg_result_dirs))
for (i in 1:length(caimg_result_dirs)) {
  caimg_result_dir = caimg_result_dirs[i]
  data.traces = read.data.trace(caimg_result_dir, filter_exp_title = 'trial')
  dates[i] = data.traces$date[i]
  animal_names[i] = data.traces$animal[i]
  binned.traces = prepare.traces(data.traces, quantile.fractions)
  if (i > 1 && animal_names[i] == animal_names[i-1]) {
    model.visited = which(models[[i-1]]$prior > 0)
    binned.traces.filtered = binned.traces[bin.xy %in% model.visited,]
    system.time(eval.res <- eval.testdata2(binned.traces.filtered, 
                                           models[[i-1]], 
                                           predict.fun=bayesmax,
                                           error.fun=bin.distance.error(xybins, xybins),
                                           stim.var=bin.xy,
                                           nstim.bins=xybins^2,
                                           value.var=response_bin))
    eval.res$df$test_date = dates[i]
    eval.res$df$model_date = dates[i-1]
    eval.res$df$animal = animal_names[i]
    otherday.decoding.df = bind_rows(otherday.decoding.df, eval.res$df)
  }
  filtered.dfs = filter.sampled(binned.traces, binned.traces[1,], min.samples=10)
  models[[i]] = create.discrete.bayes(filtered.dfs$train, 
                                      nstim.bins=xybins^2,
                                      value.var=response_bin,
                                      stim.var=bin.xy)
}
```

```{r}
otherday.decoding.df = otherday.decoding.df %>%
  left_join(mouse.meta.df, by='animal') %>%
  left_join(trials.meta.df, by=c("animal", "test_date"="date"))

otherday.decoding.df = data.table(otherday.decoding.df)
otherday.perf = otherday.decoding.df[, .(med=median(error)), by=c('test_date', 'animal')] 
otherday.perf$med %>% summary

ggplot(otherday.decoding.df, aes(x=model_date, y=error, color=animal)) +
  geom_boxplot()
```



Mean error per bin
```{r}
decoding.df %>%
  group_by(date, animal, bin.xy) %>%
  dplyr::summarise(mean.error=mean(error),
                   median.error=median(error),
                   sem.error=sem(error),
                   ntests=n(),
                   prior=prior[1]) -> mean.error.df
mean.error.df %>%  
  DT::datatable() %>%
  DT::formatRound(columns=c('mean.error', 'median.error', 'sem.error', 'prior'), digits = 3)

ggplot(mean.error.df)  + geom_point(aes(x=prior, y=mean.error), alpha=0.1) +
  xlim(c(0,0.07))
```


